# -*- coding: utf-8 -*-
"""Dehaze_Former.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OD_DvOGgpWstNQ5tcU7SxPDk4ms3vQ8d
"""

import torch
import cv2
import numpy as np
import matplotlib.pyplot as plt
from models.dehazeformer import DehazeFormer

def load_model():
    model = DehazeFormer(
        in_chans=3,
        out_chans=4,     # MUST match pretrained weights
        window_size=8,
        embed_dims=[24, 48, 96, 48, 24],
        mlp_ratios=[2., 4., 4., 2., 2.],
        depths=[4, 4, 4, 4, 4],
        num_heads=[2, 4, 6, 4, 2],
        attn_ratio=[1/4, 1/2, 3/4, 1/2, 1/4]
    )

    ckpt = torch.load(
        "/content/DehazeFormer/save_models/outdoor/dehazeformer_m_outdoor.pth",
        map_location="cpu"
    )
    state = ckpt["model"] if "model" in ckpt else ckpt
    model.load_state_dict(state, strict=False)
    model.eval()

    return model.cuda() if torch.cuda.is_available() else model

def visibility_amplify(img):
    img = img.astype(np.float32) / 255.0

    mean = img.mean()
    gamma = 1.0 + (0.6 if mean > 0.55 else 0.35)
    img = np.power(img, gamma)

    p1, p99 = np.percentile(img, (1, 99))
    img = np.clip((img - p1) / (p99 - p1 + 1e-6), 0, 1)

    return (img * 255).astype(np.uint8)

def object_emphasis(img):
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    edges = cv2.Canny(gray, 60, 150)
    edges = cv2.dilate(edges, None)

    img = img.copy()
    img[edges > 0] = np.clip(img[edges > 0] * 1.25, 0, 255)

    return img

def stabilize_color(img):
    img = img.astype(np.float32)
    avg = img.mean(axis=(0,1))
    gray = avg.mean()

    for c in range(3):
        img[:,:,c] *= gray / (avg[c] + 1e-6)

    return np.clip(img, 0, 255).astype(np.uint8)

img = cv2.imread("/content/hazy-5.jpg")
assert img is not None, "❌ Image not found"

img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

model = load_model()

inp = torch.from_numpy(img_rgb / 255.0).float()
inp = inp.permute(2, 0, 1).unsqueeze(0)
inp = inp.cuda() if torch.cuda.is_available() else inp

with torch.no_grad():
    out = model(inp)

# Dehazed RGB is in first 3 channels
out = out[:, :3]

out_np = out.squeeze(0).permute(1, 2, 0).cpu().numpy()
out_np = np.clip(out_np, 0, 1)
out_np = (out_np * 255).astype(np.uint8)

result = out_np.copy()

result = visibility_amplify(result)
result = object_emphasis(result)
result = stabilize_color(result)

# ✅ OPTIONAL MICRO-SMOOTH (REMOVE GRID / DOT PATTERN)
result = cv2.bilateralFilter(
    result,
    d=5,
    sigmaColor=30,
    sigmaSpace=30
)

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.title("Original")
plt.imshow(img_rgb)
plt.axis("off")

plt.subplot(1,2,2)
plt.title("Enhanced Visibility Output")
plt.imshow(result)
plt.axis("off")

plt.show()

