# -*- coding: utf-8 -*-
"""FYP_video.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F6yVDHpJVJ19RRLJK69u6ygdf860T_x6
"""

!pip install -q torch torchvision timm opencv-python einops tqdm

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/IDKiro/DehazeFormer.git
# %cd DehazeFormer
!pip install -q torch torchvision timm opencv-python einops
!mkdir -p save_models/indoor save_models/outdoor save_models/rshaze save_models/reside6k
print("Setup complete. Upload weights next.")

!ls save_models/outdoor

from models.dehazeformer import DehazeFormer
print("✅ DehazeFormer imported correctly")

import torch
import cv2
import numpy as np
import os
import gc
from tqdm import tqdm

from models.dehazeformer import DehazeFormer

def load_model():
    model = DehazeFormer(
        in_chans=3,
        out_chans=4,
        window_size=8,
        embed_dims=[24, 48, 96, 48, 24],
        mlp_ratios=[2., 4., 4., 2., 2.],
        depths=[4, 4, 4, 4, 4],
        num_heads=[2, 4, 6, 4, 2],
        attn_ratio=[1/4, 1/2, 3/4, 1/2, 1/4]
    )

    ckpt = torch.load(
        "save_models/outdoor/dehazeformer_m_outdoor.pth",
        map_location="cpu"
    )
    state = ckpt["model"] if "model" in ckpt else ckpt
    model.load_state_dict(state, strict=False)
    model.eval()

    return model.cuda() if torch.cuda.is_available() else model

def visibility_amplify(img):
    img = img.astype(np.float32) / 255.0
    mean = img.mean()
    gamma = 1.0 + (0.6 if mean > 0.55 else 0.35)
    img = np.power(img, gamma)
    p1, p99 = np.percentile(img, (1, 99))
    img = np.clip((img - p1) / (p99 - p1 + 1e-6), 0, 1)
    return (img * 255).astype(np.uint8)

def object_emphasis(img):
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    edges = cv2.Canny(gray, 60, 150)
    edges = cv2.dilate(edges, None)
    img = img.copy()
    img[edges > 0] = np.clip(img[edges > 0] * 1.25, 0, 255)
    return img

def stabilize_color(img):
    img = img.astype(np.float32)
    avg = img.mean(axis=(0,1))
    gray = avg.mean()
    for c in range(3):
        img[:,:,c] *= gray / (avg[c] + 1e-6)
    return np.clip(img, 0, 255).astype(np.uint8)

import torch
import cv2
import numpy as np
import gc
from tqdm import tqdm

from models.dehazeformer import DehazeFormer

print("✅ Imports OK")

def load_model():
    model = DehazeFormer(
        in_chans=3,
        out_chans=4,   # MUST match pretrained weights
        window_size=8,
        embed_dims=[24, 48, 96, 48, 24],
        mlp_ratios=[2., 4., 4., 2., 2.],
        depths=[4, 4, 4, 4, 4],
        num_heads=[2, 4, 6, 4, 2],
        attn_ratio=[1/4, 1/2, 3/4, 1/2, 1/4]
    )

    ckpt = torch.load(
        "save_models/outdoor/dehazeformer_m_outdoor.pth",
        map_location="cpu"
    )

    state = ckpt["model"] if "model" in ckpt else ckpt
    model.load_state_dict(state, strict=False)
    model.eval()

    if torch.cuda.is_available():
        model = model.cuda()

    return model

model = load_model()
print("✅ Model loaded")

def visibility_amplify(img):
    img = img.astype(np.float32) / 255.0
    mean = img.mean()
    gamma = 1.0 + (0.6 if mean > 0.55 else 0.35)
    img = np.power(img, gamma)
    p1, p99 = np.percentile(img, (1, 99))
    img = np.clip((img - p1) / (p99 - p1 + 1e-6), 0, 1)
    return (img * 255).astype(np.uint8)

def object_emphasis(img):
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    edges = cv2.Canny(gray, 60, 150)
    edges = cv2.dilate(edges, None)
    img = img.copy()
    img[edges > 0] = np.clip(img[edges > 0] * 1.25, 0, 255)
    return img

def stabilize_color(img):
    img = img.astype(np.float32)
    avg = img.mean(axis=(0,1))
    gray = avg.mean()
    for c in range(3):
        img[:,:,c] *= gray / (avg[c] + 1e-6)
    return np.clip(img, 0, 255).astype(np.uint8)

from google.colab import files

print("Upload hazy video (mp4)")
uploaded = files.upload()

for fn in uploaded:
    !mv "{fn}" hazy_video.mp4

print("✅ Video uploaded")

"""from google.colab import files
files.download("dehazed_outdoor.mp4")

"""

# ===== LOAD DEHAZEFORMER MODEL (CORRECT) =====

model = load_model()
model.eval()

print("✅ Model loaded and ready")

cap = cv2.VideoCapture("hazy_video.mp4")

fps = cap.get(cv2.CAP_PROP_FPS)
orig_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
orig_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

fourcc = cv2.VideoWriter_fourcc(*"mp4v")
out = cv2.VideoWriter(
    "dehazed_outdoor.mp4",
    fourcc,
    fps,
    (orig_w, orig_h)
)

prev_frame = None
prev_lattice = None

print("🚀 Processing video...")

def remove_pixel_lattice(img):
    f = img.astype(np.float32)

    smooth = cv2.GaussianBlur(f, (3, 3), 0.6)

    gray = cv2.cvtColor(f.astype(np.uint8), cv2.COLOR_RGB2GRAY)
    edges = cv2.Canny(gray, 80, 160)
    edges = cv2.dilate(edges, None)

    alpha = 0.14  # 🔒 SAME EFFECT, LESS DETAIL LOSS
    f[edges == 0] = (1 - alpha) * f[edges == 0] + alpha * smooth[edges == 0]

    return f


def slight_saturation_boost(img):
    hsv = cv2.cvtColor(img.astype(np.uint8), cv2.COLOR_RGB2HSV).astype(np.float32)
    hsv[..., 1] *= 1.03  # 🔒 VERY SLIGHT (3%) — no darkening
    return cv2.cvtColor(np.clip(hsv, 0, 255).astype(np.uint8), cv2.COLOR_HSV2RGB)


while True:
    ret, frame = cap.read()
    if not ret:
        break

    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    inp = torch.from_numpy(rgb / 255.0).float()
    inp = inp.permute(2,0,1).unsqueeze(0)
    if torch.cuda.is_available():
        inp = inp.cuda()

    with torch.no_grad():
        out_tensor = model(inp)[:, :3]

    # 🔒 KEEP FLOAT — NO EARLY QUANTIZATION
    out_tensor = out_tensor.clamp(0, 1)
    out_np = (out_tensor * 255.0).squeeze(0).permute(1,2,0).cpu().numpy()

    # 🔒 SAME enhancement stack
    result = visibility_amplify(out_np)
    result = object_emphasis(result)
    result = stabilize_color(result)

    result = cv2.bilateralFilter(result.astype(np.uint8), 5, 30, 30).astype(np.float32)

    # 🔒 lattice suppression (float domain)
    result = remove_pixel_lattice(result)

    # 🔒 tiny saturation recovery (visual clarity only)
    result = slight_saturation_boost(result)

    # 🔒 lattice temporal stability
    if prev_lattice is not None:
        result = 0.92 * result + 0.08 * prev_lattice
    prev_lattice = result.copy()

    # 🔒 original temporal stability
    if prev_frame is not None:
        result = 0.85 * result + 0.15 * prev_frame
    prev_frame = result.copy()

    # 🔒 FINAL conversion ONLY HERE
    out.write(
        cv2.cvtColor(
            np.clip(result, 0, 255).astype(np.uint8),
            cv2.COLOR_RGB2BGR
        )
    )

    del inp, out_tensor
    torch.cuda.empty_cache()
    gc.collect()

cap.release()
out.release()

print("✅ Video saved as dehazed_outdoor.mp4")

from google.colab import files
files.download("dehazed_outdoor.mp4")

