# -*- coding: utf-8 -*-
"""FYP_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DcMnalPwpV1vJ6WMIUVc0688Pbm409KM
"""

# Commented out IPython magic to ensure Python compatibility.
# TRULY INTELLIGENT DEHAZING SYSTEM - AGGRESSIVE & EFFECTIVE
# Complete 11-cell Colab code

# ============================================================================
# CELL 1: Install Dependencies
# ============================================================================
!pip install -q torch torchvision timm opencv-python einops tqdm

# ============================================================================
# CELL 2: Clone Repository
# ============================================================================
!git clone https://github.com/IDKiro/DehazeFormer.git
# %cd DehazeFormer
!pip install -q torch torchvision timm opencv-python einops

# ============================================================================
# CELL 3: Create Directories
# ============================================================================
!mkdir -p save_models/outdoor
print("✅ Upload weights to save_models/outdoor/")

# ============================================================================
# CELL 4: Upload Weights
# ============================================================================
from google.colab import files
uploaded = files.upload()
for filename in uploaded:
    !mv "{filename}" save_models/outdoor/dehazeformer_m_outdoor.pth
!ls -lh save_models/outdoor/

# ============================================================================
# CELL 5: Import Libraries
# ============================================================================
import torch
import cv2
import numpy as np
import gc
from tqdm import tqdm
import torch.nn.functional as F
from models.dehazeformer import DehazeFormer
print("✅ Imports OK")

# ============================================================================
# CELL 6: Load Model
# ============================================================================
def load_model():
    model = DehazeFormer(
        in_chans=3, out_chans=4, window_size=8,
        embed_dims=[24, 48, 96, 48, 24],
        mlp_ratios=[2., 4., 4., 2., 2.],
        depths=[4, 4, 4, 4, 4],
        num_heads=[2, 4, 6, 4, 2],
        attn_ratio=[1/4, 1/2, 3/4, 1/2, 1/4]
    )
    ckpt = torch.load("save_models/outdoor/dehazeformer_m_outdoor.pth", map_location="cpu")
    model.load_state_dict(ckpt.get("model", ckpt), strict=False)
    model.eval()
    return model.cuda() if torch.cuda.is_available() else model

model = load_model()
print("✅ Model loaded")

# ============================================================================
# CELL 7: CRISP Post-Processing Functions
# ============================================================================

def adaptive_unsharp_mask(img, amount=1.2, threshold=0):
    """Professional sharpening (Unsharp Mask) - crisp but not overpowered"""
    img_float = img.astype(np.float32)
    # Target 3x3 gaussian for high-frequency extraction
    blurred = cv2.GaussianBlur(img_float, (3, 3), 1.0)
    sharpened = float(amount + 1) * img_float - float(amount) * blurred
    sharpened = np.clip(sharpened, 0, 255).astype(np.uint8)

    if threshold > 0:
        low_contrast_mask = np.absolute(img_float - blurred) < threshold
        np.copyto(sharpened, img, where=low_contrast_mask)

    return sharpened

def crisp_visibility_amplify(img, smoothed_mean):
    """Visibility enhancement using smoothed metrics to kill flicker"""
    img = img.astype(np.float32) / 255.0

    # Use smoothed_mean instead of per-frame mean to ensure zero flicker
    if smoothed_mean < 0.35:
        gamma = 0.88
    elif smoothed_mean < 0.50:
        gamma = 0.94
    else:
        gamma = 1.0

    img = np.power(img, gamma)

    # Balanced contrast stretch
    p1, p99 = np.percentile(img, (1.2, 98.8))
    img = np.clip((img - p1) / (p99 - p1 + 1e-6), 0, 1)

    return (img * 255).astype(np.uint8)

def balanced_color_correction(img):
    """Deep natural color stabilization"""
    img = img.astype(np.float32)
    avg = img.mean(axis=(0, 1))
    gray = avg.mean()

    # Gentle correction to preserve natural forest look
    for c in range(3):
        target = gray / (avg[c] + 1e-6)
        img[:, :, c] *= (0.7 + 0.3 * target) # Weighted toward original

    img = np.clip(img, 0, 255).astype(np.uint8)

    # Adaptive saturation boost
    hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV).astype(np.float32)
    sat_mean = hsv[:, :, 1].mean()

    boost = 1.35 if sat_mean < 50 else 1.22 if sat_mean < 75 else 1.12
    hsv[:, :, 1] = np.clip(hsv[:, :, 1] * boost, 0, 255)

    return cv2.cvtColor(hsv.astype(np.uint8), cv2.COLOR_HSV2RGB)

print("✅ Crisp & Stable logic defined")

# ============================================================================
# CELL 8: Upload Video
# ============================================================================
from google.colab import files
uploaded = files.upload()
for filename in uploaded:
    !mv "{filename}" hazy_video.mp4

cap_test = cv2.VideoCapture("hazy_video.mp4")
if cap_test.isOpened():
    fps = cap_test.get(cv2.CAP_PROP_FPS)
    width = int(cap_test.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap_test.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap_test.get(cv2.CAP_PROP_FRAME_COUNT))
    print(f"📹 {width}x{height} @ {fps} FPS, {total_frames} frames")
    cap_test.release()

# ============================================================================
# CELL 9: ZERO-FLICKER CRISP PROCESSING
# ============================================================================
print("✨ INITIALIZING CRISP DEHAZING ENGINE...\\n")

MEAN = torch.tensor([0.485, 0.456, 0.406]).view(1, 1, 3)
STD = torch.tensor([0.229, 0.224, 0.225]).view(1, 1, 3)
if torch.cuda.is_available():
    MEAN, STD = MEAN.cuda(), STD.cuda()

cap = cv2.VideoCapture("hazy_video.mp4")
fps = cap.get(cv2.CAP_PROP_FPS)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter("dehazed_crisp.mp4", fourcc, fps, (width, height))

prev_frame = None
pbar = tqdm(total=total_frames, desc="💎 Crisp & Clear")

# EMA Metrics to kill flickering (Exponential Moving Average)
ema_mean = None
ema_alpha = 0.15 # 15% current, 85% history for massive stability

frame_count = 0
while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    h, w, _ = rgb.shape

    # 8-pixel alignment
    new_h, new_w = (h + 7) // 8 * 8, (w + 7) // 8 * 8
    pad_h, pad_w = new_h - h, new_w - w

    # Normalize
    inp = torch.from_numpy(rgb / 255.0).float()
    if torch.cuda.is_available():
        inp = inp.cuda()
    inp = (inp - MEAN) / STD
    inp = inp.permute(2, 0, 1).unsqueeze(0)
    inp = F.pad(inp, (0, pad_w, 0, pad_h), mode='reflect')

    # Inference
    with torch.no_grad():
        out_tensor = model(inp)[:, :3]

    # Denormalize
    out_tensor = out_tensor[:, :, :h, :w].squeeze(0).permute(1, 2, 0)
    out_tensor = (out_tensor * STD) + MEAN
    out_tensor = out_tensor.clamp(0, 1)

    # Aggressive but crystal clear model boost
    out_tensor = torch.pow(out_tensor, 0.82)
    out_tensor = out_tensor.clamp(0, 1)

    result = (out_tensor.cpu().numpy() * 255.0).astype(np.uint8)

    # --- CRISP POST-PROCESSING ---

    # 1. Update EMA Metrics (Prevents jumping/flickering)
    current_mean = result.mean() / 255.0
    if ema_mean is None:
        ema_mean = current_mean
    else:
        ema_mean = (ema_alpha * current_mean) + (1 - ema_alpha) * ema_mean

    # 2. Enhance Visibility using stable metrics
    result = crisp_visibility_amplify(result, ema_mean)

    # 3. Apply Unsharp Mask for professional crispness
    result = adaptive_unsharp_mask(result, amount=0.6, threshold=2) # Gentle but sharp

    # 4. Stabilize Color
    result = balanced_color_correction(result)

    # 5. Lightweight Grid Removal (d=3 prevents MUSHY texture)
    result = cv2.bilateralFilter(result, d=3, sigmaColor=35, sigmaSpace=25)

    # --- TEMPORAL CONSISTENCY ---
    if prev_frame is not None:
        # 0.85/0.15 blend to keep results SHARP (stops ghosting/mush)
        result = cv2.addWeighted(result, 0.85, prev_frame, 0.15, 0)
    prev_frame = result.copy()

    out.write(cv2.cvtColor(result, cv2.COLOR_RGB2BGR))
    pbar.update(1)

    if frame_count % 30 == 0:
        del inp, out_tensor
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()

pbar.close()
cap.release()
out.release()
print(f"\\n✅ Professional Crisp Dehazing Done! Processed {frame_count} frames.")

# ============================================================================
# CELL 9.5: High Resolution Preview
# ============================================================================
import matplotlib.pyplot as plt
cap_h = cv2.VideoCapture("hazy_video.mp4")
cap_d = cv2.VideoCapture("dehazed_crisp.mp4")
pos = [total_frames//6, total_frames//2, 5*total_frames//6]
fig, axes = plt.subplots(3, 2, figsize=(18, 16))
for idx, p in enumerate(pos):
    cap_h.set(cv2.CAP_PROP_POS_FRAMES, p)
    ret1, h1 = cap_h.read()
    cap_d.set(cv2.CAP_PROP_POS_FRAMES, p)
    ret2, d1 = cap_d.read()
    if ret1 and ret2:
        axes[idx,0].imshow(cv2.cvtColor(h1, cv2.COLOR_BGR2RGB))
        axes[idx,0].set_title(f"Hazy Frame {p}", fontsize=12, fontweight='bold'); axes[idx,0].axis('off')
        axes[idx,1].imshow(cv2.cvtColor(d1, cv2.COLOR_BGR2RGB))
        axes[idx,1].set_title(f"CRISP & CLEAR {p}", fontsize=12, fontweight='bold', color='green'); axes[idx,1].axis('off')
plt.tight_layout(); plt.show()
cap_h.release(); cap_d.release()

# ============================================================================
# CELL 10: Download
# ============================================================================
from google.colab import files
files.download("dehazed_crisp.mp4")

# ============================================================================
# CELL 10: Download
# ============================================================================
from google.colab import files
files.download("dehazed_crisp.mp4")

